### ISSUE TITLE
Authentication issue with GitHub npm registry

### ISSUE THREAD

**Issue by sonallux** [jvalue/node-dry#1]
@georg-schwarz I think I know how to fix the authentication issue you told me. You must use the [setup-node](https://github.com/actions/setup-node) action. 

This snippet should work for publishing packages to Github npm registry. This is also mentioned in their README and I have used this also successfully in the past.
```yaml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v1
  with:
    node-version: '14.x'
    registry-url: 'https://npm.pkg.github.com'
- run: npm install
- run: npm publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
